version: "3.9"

services:

  extrolabs_nginx:
    container_name: extrolabs_nginx
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/error.log:/var/log/nginx/error.log
      - ./data/nginx/access.log:/var/log/nginx/access.log
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - "80:80"
      - "443:443"
    network_mode: host
    depends_on:
      - extrolabs_certbot

  extrolabs_db:
    container_name: extrolabs_db
    image: postgres
    restart: unless-stopped
    volumes:
      - /mnt/raid0/extrolabs_db/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_SSL_MODE: ${DB_SSL_MODE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d extrolabs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # ports: 
    #  - "5432:5432"
    networks:
      - extrolabs_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  extrolabs_gogs:
    container_name: extrolabs_gogs
    build:
      context: ./gogs
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /mnt/raid0/extrolabs_gogs/var/gogs:/data
    depends_on:
      - extrolabs_db
    ports:
      - "9022:9022"
      - "9880:3000"
    networks:
      - extrolabs_network

  extrolabs_certbot:
    container_name: extrolabs_certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/log:/var/log/letsencrypt"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

networks:
  extrolabs_network:
