version: "3.9"

services:

  extrolabs_nginx:
    image: nginx:stable
    restart: unless-stopped
    container_name: extrolabs_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/var/log/nginx/error.log
      - ./nginx/access.log:/var/log/nginx/access.log
      - "/mnt/raid0/etc/letsencrypt:/etc/letsencrypt"
      - "/mnt/raid0/var/lib/letsencrypt:/var/lib/letsencrypt"
    ports:
      - "80:80"
    network_mode: host
    depends_on:
      - extrolabs_certbot

  extrolabs_db:
    image: postgres
    restart: unless-stopped
    container_name: extrolabs_db
    environment:
      POSTGRES_DB: extrolabs
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 81903812737316853165316
      POSTGRES_SSL_MODE: disable
    # ports: 
    #  - "5432:5432"
    volumes:
      - extrolabs-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d extrolabs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - extrolabs_network

  extrolabs_gogs:
    image: gogs/gogs:latest
    container_name: extrolabs_gogs
    restart: unless-stopped
    ports:
      - "9022:22"
      - "9880:3000"
    volumes:
      - gogs-data:/data
    environment:
      - SOCAT_LINK=true
      - RUN_CROND=false
    depends_on:
      - extrolabs_db
    networks:
      - extrolabs_network

  extrolabs_certbot:
    image: certbot/certbot:latest
    container_name: extrolabs_certbot
    restart: unless-stopped
    volumes:
      - "/mnt/raid0/etc/letsencrypt:/etc/letsencrypt"
      - "/mnt/raid0/var/lib/letsencrypt:/var/lib/letsencrypt"
    healthcheck:
      test: ["CMD-SHELL", "certbot renew --quiet || exit 0"]
      interval: 720h
      timeout: 1h
      retries: 5
      start_period: 10s
    command: certonly --standalone --preferred-challenges http --agree-tos --no-eff-email -d gogs.extrolabs.ru
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

networks:
  extrolabs_network:

volumes:
  extrolabs-db-data:
    driver: local
    driver_opts:
      device: /mnt/raid0/extrolabs-db-data
  gogs-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/raid0/var/gogs
      o: bind